# azure-pipelines.yml
trigger:
  - none  # Disable automatic triggers, so this pipeline only runs manually

pr:
  - none  # Disable PR triggers

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build agent

stages:
- stage: Rebase_Airflow_Fork
  jobs:
  - job: GitPull
    steps:
    - checkout: self  # Check out the repository so we can rebase it
    - script: |
        echo "Configuring Git..."
        git config --global user.name "Ambika Garg"
        git config --global user.email "ambikagarg1101@gmail.com"

        git pull

        echo "Adding upstream remote..."
        git remote add upstream https://github.com/apache/airflow.git

        echo "Fetching upstream..."
        git fetch upstream

        echo "Checking out branch..."
        git checkout dev-fabric

        echo "Rebasing with upstream..."
        git rebase upstream/main

        echo "Pushing changes to origin..."
        git push https://$(GITHUB_PAT)@github.com/ambika-garg/airflow.git dev-fabric --force-with-lease
      displayName: 'Rebase Fork with Upstream'
      env:
        GIT_ASKPASS: echo
        GIT_PASSWORD: $(GITHUB_PAT)  # Ensure this is set up correctly in Azure DevOps
