---
name: System dashboard workflow for Microsoft Fabric
on:  # yamllint disable-line rule:truthy
  # schedule: []  # Disable the default schedule
  workflow_dispatch:  # Allows manual triggering
jobs:
  rebase:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AIRFLOW_FORK_TOKEN }}
          persist-credentials: false

      # Later on set it as common step
      - name: Set Up Git
        run: |
          git config --global user.name "Ambika Garg"
          git config --global user.email "ambikagarg1101@gmail.com"

      - name: Git Pull
        run: |
          git pull
          git branch -a

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/apache/airflow.git
          git fetch upstream

      - name: Rebase Dev-Fork with Upstream
        run: |
          git checkout dev-fabric
        # git rebase upstream/main
        # git push https://${{ secrets.AIRFLOW_FORK_TOKEN }}@github.com/ambika-garg/airflow.git \
        # dev-fabric --force-with-lease

      - name: Install Breeze
        uses: ./.github/actions/breeze
      - name: Run System Tests for Microsoft Fabric Provider
        id: system-tests-for-microsoft-fabric
        env:
          SYSTEM_TESTS_FABRIC_DATASET_ID: "${{ secrets.DATASET_ID }}"
          SYSTEM_TESTS_FABRIC_GROUP_ID: "${{ secrets.GROUP_ID }}"
          SYSTEM_TESTS_FABRIC_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
          # SYSTEM_TESTS_FABRIC_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
          SYSTEM_TESTS_FABRIC_REFRESH_TOKEN: "${{ secrets.REFRESH_TOKEN }}"
          SYSTEM_TESTS_FABRIC_TENANT_ID: "${{ secrets.TENANT_ID }}"
        run: |
          export BREEZE_INIT_COMMAND="export SYSTEM_TESTS_FABRIC_CLIENT_ID=${SYSTEM_TESTS_FABRIC_CLIENT_ID} \
            && export SYSTEM_TESTS_FABRIC_REFRESH_TOKEN=${SYSTEM_TESTS_FABRIC_REFRESH_TOKEN} \
            && export SYSTEM_TESTS_FABRIC_TENANT_ID=${SYSTEM_TESTS_FABRIC_TENANT_ID}"

          printenv SYSTEM_TESTS_FABRIC_CLIENT_ID

          breeze testing tests \
          tests/system/providers/microsoft/fabric/example_fabric_notebook_run.py \
          tests/system/providers/microsoft/fabric/example_fabric_pipeline_run.py \
          tests/system/providers/microsoft/fabric/example_mock_system_test.py \
          --system microsoft \
          --junitxml=tests/pytest-report.xml

      - name: Upload Raw System Test Report to Github artifact storage
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: pytest-report
          path: tests/pytest-report.xml  # path of the file to upload

      - name: Upload System Test report to Azure Blob storage
        uses: fixpoint/azblob-upload-artifact@v4
        if: success() || failure()
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          name: pytest-report.xml
          container: airflow-system-dashboard-input
          path: tests/pytest-report.xml

  preprocess:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.repository }}
      GITHUB_RUN_ID: ${{ github.run_id }}
    needs: rebase
    if: success() || failure()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AIRFLOW_FORK_TOKEN }}
          persist-credentials: false

      - name: Set Up Git
        run: |
          git config --global user.name "Ambika Garg"
          git config --global user.email "ambikagarg1101@gmail.com"

      - name: Download System Test Report
        uses: actions/download-artifact@v3
        with:
          name: pytest-report
          path: pytest-report

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-storage-blob azure-identity

      - name: Convert Report to JSON and upload to Azure Blob Storage
        run: |
          python .github/scripts/process_artifact.py

      - name: Consolidate last k runs and upload to Azure Blob Storage
        run: |
          python .github/scripts/process_last_k_runs.py

  display-system-tests:
    runs-on: ubuntu-latest
    needs: preprocess
    if: success() || failure()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AIRFLOW_FORK_TOKEN }}
          persist-credentials: false

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    # Step 2: Download the file from Azure Blob Storage
      - name: Download Consolidated-K-Run Report from Azure Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          az storage blob download \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --account-key $AZURE_STORAGE_KEY \
            --container-name consolidate-blob \
            --name gold-report.json \
            --file ./report.json

      - name: Push Test file to Dashboard Repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AIRFLOW_FORK_TOKEN }}
        with:
          source_file: 'report.json'
          destination_repo: 'ambika-garg/fabric-airflow-system-dashboard'
          destination_folder: '_data'
          user_email: 'ambikagarg1101@gmail.com'
          user_name: 'Ambika Garg'
          commit_message: 'Add test report to dashboard repo'
