---
name: System dashboard workflow for Microsoft Azure
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:  # Allows manual triggering
jobs:
  rebase:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AIRFLOW_FORK_TOKEN }}

      - name: Set Up Git
        run: |
          git config --global user.name "Ambika Garg"
          git config --global user.email "ambikagarg1101@gmail.com"

      - name: Git Pull
        run: |
          git pull --unshallow

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/apache/airflow.git
          git fetch upstream

      - name: Rebase Fork with Upstream
        run: |
          git checkout main
          git rebase upstream/main
          git push origin main --force-with-lease

  run-system-tests:
    runs-on: ubuntu-latest
    needs: [rebase]
    steps:
      - name: "Check Github repo"
        run: |
          git remote -v
          git branch
          git log --oneline --graph --all 
      - name: "Install Breeze"
        uses: ./.github/actions/breeze
      - name: Test with pytest
        run: |
          pip install pytest
          pytest --system microsoft.azure tests/system/providers/microsoft/azure