---
name: System dashboard workflow for Microsoft Azure
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allows manual triggering
jobs:
  rebase:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AIRFLOW_FORK_TOKEN }}

      - name: Set Up Git
        run: |
          git config --global user.name "Ambika Garg"
          git config --global user.email "ambikagarg1101@gmail.com"

      - name: Git Pull
        run: |
          git pull --unshallow

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/apache/airflow.git
          git fetch upstream

      # - name: Rebase Fork with Upstream
      #   run: |
      #     git checkout main
      #     git rebase upstream/main
      #     git push origin main --force-with-lease
      
      - name: Rebase Fork with Upstream
        run: |
          git checkout fabric
          git rebase upstream/main
          git push origin fabric --force-with-lease

      # - name: "Install Breeze"
      #   uses: ./.github/actions/breeze
      # - name: "Run System Tests for Microsoft Azure"
      #   env: 
      #     DATASET_ID: ${{ secrets.DATASET_ID }}
      #     GROUP_ID: ${{ secrets.GROUP_ID }}
      #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      #     TENANT_ID: ${{ secrets.TENANT_ID }}
      #   run: |
      #     breeze testing tests tests/system/providers/microsoft/azure/example_mock_test.py tests/system/providers/microsoft/azure/example_powerbi_dataset_refresh.py --system microsoft --junitxml=tests/pytest-report.xml
        
      # - name: Upload Test report to Azure Blob storage
      #   uses: fixpoint/azblob-upload-artifact@v4
      #   if: always()
      #   with:
      #     connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      #     name: system-test-report
      #     path: tests/pytest-report.xml

      # - name: "Access Env variables"
      #   env: 
      #     DATASET_ID: ${{ secrets.DATASET_ID }}
      #     GROUP_ID: ${{ secrets.GROUP_ID }}
      #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      #     TENANT_ID: ${{ secrets.TENANT_ID }}
      #   run: |
      #     python tests/system/providers/microsoft/azure/delele_file.py

      # - name: Upload pytest report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pytest-report
      #     path: tests/system/providers/microsoft/azure/pytest_report/pytest-report.xml

      # - name: Download pytest report
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: pytest-report

